name: CI-CD

on:
  push:

  workflow_dispatch:

env:
  IMAGE_NAME: "social-network-web"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Connect and build and run on Aeza
        uses: appleboy/ssh-action@v0.1.3

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

          envs: GITHUB_REPOSITORY, IMAGE_NAME, GITHUB_REF

          script: |
            rm -r ${GITHUB_REPOSITORY#*/}
            git clone git@github.com:${{ github.repository }}.git
            cd ${GITHUB_REPOSITORY#*/}
            git switch ${GITHUB_REF##*/}
            docker rmi -zf ${IMAGE_NAME}
            docker build -t ${IMAGE_NAME} .
            docker stop ${IMAGE_NAME}
            docker rm ${IMAGE_NAME}
            docker run \
            -d -p 10:80 \
            --restart always \
            --name ${IMAGE_NAME} \
            ${IMAGE_NAME}
            docker rmi -f $(docker images -f "dangling=true" -q)

